server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
    default-filters:
      - TokenRelay
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-registry
          uri: lb://car-registry
          predicates:
            - Path=/concessionaire/**
        
security:
  oauth2:
    client:
      provider:
        keycloak:
          authorization-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/auth
          userinfo-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/userinfo
          user-name-attribute: preferred_username
          token-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/token
      registration:
        car-registry-backend:
          provider: keyloack
          client-id: car-registry-backend
          client-secret: OYWf0tr7eDi5IVTVJN9eAzTVJfVm4Eby
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/car-registry
        
       