server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-registry
          uri: lb://car-registry
          predicates:
            - Path=/concessionaire/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/realms/car-registry/protocol/openid-connect/token
            issuer-uri: http://localhost:8180/realms/car-registry
        registration:
          car-registry-backend:
            provider: keycloak
            client-id: car-registry-backend
            client-secret: kik90hg7gwqWNDWlBgX5YvqHzAnMnCXx
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/car-registry-backend
        