server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/user-service/**
          filters:
            - AuthFilter
        - id: car-registry
          uri: lb://car-registry
          predicates:
            - Path=/cars/**,/car-registry/**
          filters:
            - AuthFilter
        - id: brand-service
          uri: lb://brand-service
          predicates:
            - Path=/brands/**,/brand-service/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/auth-service/**